version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: sakila-db
      MYSQL_USER: user
      MYSQL_PASSWORD: mysql
    ports:
      - "3666:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

